############################################################
#
# web访问端口号  约定：8089
#
############################################################
server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: dev
#  datasource:                                             ## 数据源的相关配置
#    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
#    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
#    url: jdbc:mysql://localhost:3306/itzixi-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    username: root
#    password: root               # 本地数据库
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  #  redis:                    ## Redis 相关配置
#    database: 1             # Redis数据库索引（默认为0）
#    host: 192.168.1.64     # 本地 Redis服务器地址
#    port: 6379              # 本地 Redis服务器连接端口
#    password: imooc


############################################################
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
